### ISSUE TITLE
用于机械故障诊断的MAML

### ISSUE THREAD

**Issue by hu1213456** [TianyuanYang/MAML_for_Mechanical_Fault_Diagnosis#1]
数据集是怎么构建的？他的具体格式是什么了

**Comment by TianyuanYang** [comment]
1. First load the data you have collected or the downloaded publicly available datasets. If you select data from one of the sensors, then each fault category should correspond to a one-dimensional sequence of vibration signals. (Some necessary data cleaning operations can be performed, such as denoising, etc.)
2. Choose an appropriate window size (e.g. 2048. Practically the sampling frequency needs to be considered). For each category, randomly capture N segments from the vibration signal as training or test samples for that category.
3. Tune the dimensionality and naming as described in https://github.com/TianyuanYang/MAML-for-Mechanical-Fault-Diagnosis#datasets, and then store the data as npy files.

**Comment by hu1213456** [comment]
您好，可以发一下您数据集具体的格式吗（您建好的数据集）您的数据格式(category, number, length, 1)，例如 (10, 100, 1024, 1)我不太了解

**Comment by TianyuanYang** [comment]
I have added the code for data processing, which you can access and run. The instruction refers to the Datasets section of README.
