### ISSUE TITLE
Why does the accuracy of n-way k-shot decrease as k increases?

### ISSUE THREAD

**Issue by xiaoxian7557** [TianyuanYang/MAML_for_Mechanical_Fault_Diagnosis#3]
May I ask, as I am modifying the parameters in the config file during the changing working conditions, why does the accuracy decrease as k increases?

**Comment by TianyuanYang** [comment]
In general, increasing k accuracy goes up. Declines that are not too significant may also be expected, and are related to model capabilities and data quality. You could check to see if there are any anomalies in the data or if the model is overfitting.
